version: '3'

services:
  web:
    restart: always
    env_file:
      - ./src/PhotoExhibiter/.env

  db:
    restart: always
    env_file:
      - ./src/PhotoExhibiter/.env

  nginx:
    restart: always
    ports:
      - "80:80"
