version: '3'

services:
  web:
    build: ./src/PhotoExhibiter
    volumes:
      - static:/app/wwwroot/
    networks:
      - web_nw
      - db_nw
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://*:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7.19
    volumes:
      - db:/var/lib/mysql
    networks:
      - photoexhibiter_db_nw

  nginx:
    build: ./src/Nginx
    volumes:
      - static:/app/wwwroot/
    networks:
      - photoexhibiter_web_nw
    depends_on:
      - web

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge


volumes:
   db:
   static:
