version: '3'

services:
  web:
    environment:
      AppSettings__AdminEmail: "admin@email.com"
      AppSettings__AdminPassword: "P@ssw3rd!"
      ConnectionStrings__ApplicationConnectionString: "Server=db;Port=3306;Database=photoexhibiter;Uid=root;Password=P@ssw0rd!;"

  db:
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd!"

  nginx:
    ports:
      - "5000:80"
