version: '3'

services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__ApplicationConnectionString: "Server=db;Port=3306;Database=photoexhibiter;Uid=root;Password=P@ssw0rd!;"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd!"
