version: '3'

services:
  web:
    build: ./PhotoExhibiter
    volumes:
      - static:/app/wwwroot/
    networks:
      - photoexhibiter_web_nw
      - photoexhibiter_db_nw
    depends_on:
      - db
    environment:
      ConnectionStrings__ApplicationConnectionString: "Server=db;Port=3306;Database=photoexhibiter;Uid=root;Password=P@ssw0rd!;"

  db:
    image: mysql:5.7.19
    volumes:
      - db:/var/lib/mysql
    networks:
      - photoexhibiter_db_nw
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd!"

  nginx:
    build: ./Nginx
    ports:
      - "5000:80"
    volumes:
      - static:/app/wwwroot/
    networks:
      - photoexhibiter_web_nw
    depends_on:
      - web

networks:
  photoexhibiter_db_nw:
    driver: bridge
  photoexhibiter_web_nw:
    driver: bridge


volumes:
   db:
   static:
