version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "p@ssword"
      ACCEPT_EULA: "Y"
